{{- if .Values.secret.enabled }}
apiVersion: apps/v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
    {{- with .Values.secret.postgres_user }}  
    POSTGRES_USER: {{ .Values.secret.postgres_user | b64enc | quote }} 
    {{- end }}
    {{- with .Values.secret.postgres_password }}  
    POSTGRES_PASSWORD: {{ .Values.secret.postgres_password | b64enc | quote }}
    {{- end }}
    {{- with .Values.secret.postgres_db }} 
    POSTGRES_DB: {{ .Values.secret.postgres_db | b64enc | quote }}
    {{- end }}
    {{- with .Values.secret.langfuse_api_secret_key }} 
    LANGFUSE_API_SECRET_KEY: {{ .Values.secret.langfuse_api_secret_key | b64enc | quote }}
    {{- end }}
    {{- with .Values.secret.langfuse_api_public_key }} 
    LANGFUSE_API_PUBLIC_KEY: {{ .Values.secret.langfuse_api_public_key | b64enc | quote }}
    {{- end }}
    {{- with .Values.secret.database_url }} 
    DATABASE_URL:  {{ .values.secret.database_url | b64enc | quote }}
    {{- end }}
    {{- with .Values.secret.nextauth_secret }} 
    NEXTAUTH_SECRET: {{ .Values.secret.nextauth_secret | b64enc | quote }}
    {{- end }}
    {{- with .Values.secret.salt }} 
    SALT: "" {{ .Values.secret.salt | b64enc | quote }}
    {{- end }}
{{- end }}
